// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpFzt4qk9OpWSex-1NJ0mjJvaHcA8l7EI',
    appId: '1:839404533624:web:aba851017b542d757dfa8d',
    messagingSenderId: '839404533624',
    projectId: 'expense-tracker-6786e',
    authDomain: 'expense-tracker-6786e.firebaseapp.com',
    storageBucket: 'expense-tracker-6786e.firebasestorage.app',
    measurementId: 'G-N4Z87J41CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKKHmyEwBsL1YAnEoE1ITSR55J8wNArOs',
    appId: '1:839404533624:android:05a4e670cca4c0fe7dfa8d',
    messagingSenderId: '839404533624',
    projectId: 'expense-tracker-6786e',
    storageBucket: 'expense-tracker-6786e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALha-PkTnYz2aDcMn2TINbg3vgeyUrbpg',
    appId: '1:839404533624:ios:b575dbd52eaac6147dfa8d',
    messagingSenderId: '839404533624',
    projectId: 'expense-tracker-6786e',
    storageBucket: 'expense-tracker-6786e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALha-PkTnYz2aDcMn2TINbg3vgeyUrbpg',
    appId: '1:839404533624:ios:b575dbd52eaac6147dfa8d',
    messagingSenderId: '839404533624',
    projectId: 'expense-tracker-6786e',
    storageBucket: 'expense-tracker-6786e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpFzt4qk9OpWSex-1NJ0mjJvaHcA8l7EI',
    appId: '1:839404533624:web:e61dc4a38adcec3f7dfa8d',
    messagingSenderId: '839404533624',
    projectId: 'expense-tracker-6786e',
    authDomain: 'expense-tracker-6786e.firebaseapp.com',
    storageBucket: 'expense-tracker-6786e.firebasestorage.app',
    measurementId: 'G-YRRD4FBBDD',
  );
}
